/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharterRouteImport } from './routes/charter'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as MaritimeRouteImport } from './routes/maritime'
import { Route as MarketDataRouteImport } from './routes/market-data'
import { Route as ModelIntelligenceRouteImport } from './routes/model-intelligence'
import { Route as OptimizationRouteImport } from './routes/optimization'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as WhatIfRouteImport } from './routes/what-if'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterRoute = CharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const MaritimeRoute = MaritimeRouteImport.update({
  id: '/maritime',
  path: '/maritime',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketDataRoute = MarketDataRouteImport.update({
  id: '/market-data',
  path: '/market-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelIntelligenceRoute = ModelIntelligenceRouteImport.update({
  id: '/model-intelligence',
  path: '/model-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizationRoute = OptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charter': typeof CharterRoute
  '/forecast': typeof ForecastRoute
  '/maritime': typeof MaritimeRoute
  '/market-data': typeof MarketDataRoute
  '/model-intelligence': typeof ModelIntelligenceRoute
  '/optimization': typeof OptimizationRoute
  '/scenarios': typeof ScenariosRoute
  '/what-if': typeof WhatIfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charter': typeof CharterRoute
  '/forecast': typeof ForecastRoute
  '/maritime': typeof MaritimeRoute
  '/market-data': typeof MarketDataRoute
  '/model-intelligence': typeof ModelIntelligenceRoute
  '/optimization': typeof OptimizationRoute
  '/scenarios': typeof ScenariosRoute
  '/what-if': typeof WhatIfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charter': typeof CharterRoute
  '/forecast': typeof ForecastRoute
  '/maritime': typeof MaritimeRoute
  '/market-data': typeof MarketDataRoute
  '/model-intelligence': typeof ModelIntelligenceRoute
  '/optimization': typeof OptimizationRoute
  '/scenarios': typeof ScenariosRoute
  '/what-if': typeof WhatIfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charter'
    | '/forecast'
    | '/maritime'
    | '/market-data'
    | '/model-intelligence'
    | '/optimization'
    | '/scenarios'
    | '/what-if'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charter'
    | '/forecast'
    | '/maritime'
    | '/market-data'
    | '/model-intelligence'
    | '/optimization'
    | '/scenarios'
    | '/what-if'
  id:
    | '__root__'
    | '/'
    | '/charter'
    | '/forecast'
    | '/maritime'
    | '/market-data'
    | '/model-intelligence'
    | '/optimization'
    | '/scenarios'
    | '/what-if'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharterRoute: typeof CharterRoute
  ForecastRoute: typeof ForecastRoute
  MaritimeRoute: typeof MaritimeRoute
  MarketDataRoute: typeof MarketDataRoute
  ModelIntelligenceRoute: typeof ModelIntelligenceRoute
  OptimizationRoute: typeof OptimizationRoute
  ScenariosRoute: typeof ScenariosRoute
  WhatIfRoute: typeof WhatIfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter': {
      id: '/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof CharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maritime': {
      id: '/maritime'
      path: '/maritime'
      fullPath: '/maritime'
      preLoaderRoute: typeof MaritimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-data': {
      id: '/market-data'
      path: '/market-data'
      fullPath: '/market-data'
      preLoaderRoute: typeof MarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-intelligence': {
      id: '/model-intelligence'
      path: '/model-intelligence'
      fullPath: '/model-intelligence'
      preLoaderRoute: typeof ModelIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimization': {
      id: '/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof OptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharterRoute: CharterRoute,
  ForecastRoute: ForecastRoute,
  MaritimeRoute: MaritimeRoute,
  MarketDataRoute: MarketDataRoute,
  ModelIntelligenceRoute: ModelIntelligenceRoute,
  OptimizationRoute: OptimizationRoute,
  ScenariosRoute: ScenariosRoute,
  WhatIfRoute: WhatIfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
